create database course_work;
\c course_work

create table country (
	id int generated by default as identity primary key,
	short_name varchar(3),
	name varchar(40)	
);

create table city (
	id int generated by default as identity primary key,
	name varchar(40),
	country_id serial
);

alter table city add constraint fk_country_city foreign key(country_id)
references country (id) on update cascade on delete restrict;

create table stadium (
	id int generated by default as identity primary key,
	name varchar(40),
	city_id serial
);

alter table stadium add constraint fk_city_stadium foreign key(city_id)
references city (id) on update cascade on delete restrict;

create table trainer (
	id int generated by default as identity primary key,
	name varchar(40)
);

create table team (
	id int generated by default as identity primary key,
	name varchar(40),
	country_id serial,
	trainer_id serial
);

alter table team add constraint fk_country_team foreign key(country_id)
references country (id) on update cascade on delete restrict;

alter table team add constraint fk_trainer_team foreign key(trainer_id)
references trainer (id) on update cascade on delete restrict;

create table player_role (
	id int generated by default as identity primary key,
	name varchar(40)
);

create table player (
	id int generated by default as identity primary key,
	team_id serial,
	name varchar(40),
	player_role_id serial,
	age integer,
	is_substitute bool
);

alter table player add constraint fk_player_role_player foreign key(player_role_id)
references player_role (id) on update cascade on delete restrict;

create table referee (
	id int generated by default as identity primary key,
	name varchar(40),
	country_id serial
);

alter table referee add constraint fk_country_referee foreign key(country_id)
references country (id) on update cascade on delete restrict;

create table match (
	id int generated by default as identity primary key,
	stage varchar(2) check (stage in ('G', 'R', 'Q', 'S', 'F')),
	date_to_play timestamp,
	stadium_id serial,
	first_team_id serial,
	second_team_id serial,
	referee_id serial,
	first_assistant_id serial,
	second_assistant_id serial
);

alter table match add constraint fk_stadium_match foreign key(stadium_id)
references stadium (id) on update cascade on delete restrict;

alter table match add constraint fk_match_first_team 
foreign key(first_team_id) references team (id)
on update cascade on delete restrict;

alter table match add constraint fk_match_second_team 
foreign key(second_team_id) references team (id)
on update cascade on delete restrict;

alter table match add constraint fk_referee_match foreign key(referee_id)
references referee (id) on update cascade on delete restrict;

alter table match add constraint fk_first_assistant_match 
foreign key(first_assistant_id) references referee (id)
on update cascade on delete restrict;

alter table match add constraint fk_second_assistant_match 
foreign key(second_assistant_id) references referee (id)
on update cascade on delete restrict;

create table action (
	id int generated by default as identity primary key,
	action_time timestamp,
	reason varchar(40),
	type varchar(3) check(type in ('Y', 'R', 'P', 'IN', 'OUT')),
	player_id serial,
	match_id serial,
	action_id serial
);

alter table action add constraint fk_player_action 
foreign key(player_id) references player (id)
on update cascade on delete restrict;

alter table action add constraint fk_match_action 
foreign key(match_id) references match (id)
on update cascade on delete restrict;

alter table action add constraint fk_action_action 
foreign key(action_id) references action (id)
on update cascade on delete restrict;
